### ISSUE TITLE
Порядок шифрования и форматирования

### ISSUE THREAD

**Issue by Wtfman007** [iamm3chanic/ArchLinux-install#2]
В скрипте создается объем, монтируются разделы и после чего шифруются. 
Но во многих статьях, что я видел, например в [статье на хабре](https://habr.com/ru/post/420081/ )  
- сначала создается объем 
- потом шифрованный контейнер 
- внутри него форматируется+монтируется файловая система.  
А в [этой статье](https://rtfm.co.ua/arch-linux-ustanovka-s-lvm-i-luks-shifrovaniem-diska/) 
- сначала шифрованный контейнер
- потом объемы 
- потом форматирование+монтирование.
Я знаю, что любой из методов создает рабочую (с точки зрения пользователя) систему. Но как делать _правильно_?

**Comment by iamm3chanic** [comment]
Спасибо за замечание!  
На самом деле, шифровать корректно в любой момент времени. Главное, чтобы созданные контейнеры с логическим объемом можно было **менять в размере**, и чтобы данные не уничтожались.  
Мой скрипт тестировался много раз, и именно в таком расположении получилась, по моему мнению, самая стабильная система.  
Но в последующих версиях я думаю сделать шифрованный контейнер **перед** монтированием разделов, а эту экзотическую версию поместить в другую ветку.

**Comment by iamm3chanic** [comment]
Теперь шифрованный контейнер создается перед монтированием в версии **dev**.
